### ISSUE TITLE
Fix intro text in iPhone 5s view

### ISSUE THREAD

**Issue by BraydenTW** [bakera33/bakera33.github.io#1]
In the chrome dev tools, I checked the responsiveness for the iPhone 5s model and ones smaller than it and the text that says "I’m Andrew, an experience designer based in Grand Rapids." is covered by the navbar on the top.

**Comment by bakera33** [comment]
Thank you, just updated that if you want to check it out again.

On Mar 30, 2020, at 2:48 PM, Brayden W <notifications@github.com<mailto:notifications@github.com>> wrote:



In the chrome dev tools, I checked the responsiveness for the iPhone 5s model and ones smaller than it and the text that says "I’m Andrew, an experience designer based in Grand Rapids." is covered by the navbar on the top.

**Comment by BraydenTW** [comment]
Ok. Looks great! You've got a bright future!
